[package]
name = "rust_math"  # Generated object will be "RustMath"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
whitehall = { path = "../../../build/generated/ffi_macro" }
jni = "0.21"
# Whitehall will auto-generate the local ffi macro during build
