[package]
name = "rust_json_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
whitehall-ffi-macro = { path = "../../../../../../whitehall-ffi-macro" }
jni = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
