[package]
name = "math"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
whitehall = { path = "./ffi_macro" }
jni = "0.21"
# Whitehall will auto-generate the local ffi macro during build
